backend:
  name: github
  repo: Heyxier/yolongtec-website-v8
  branch: main
  commit_messages:
    create: 'Create {{slug}}'
    update: 'Update {{slug}}'
    delete: 'Delete {{slug}}'
    uploadMedia: 'Upload {{path}}'
    deleteMedia: 'Delete {{path}}'

media_folder: images
public_folder: /images

collections:
  - name: articles
    label: 文章管理
    folder: _articles
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 标题, name: title, widget: string}
      - {label: 分类, name: category, widget: select, options: [news, product, about]}
      - {label: 发布日期, name: publishedAt, widget: datetime}
      - {label: 摘要, name: excerpt, widget: textarea, required: false}
      - {label: 封面图, name: coverImage, widget: image, required: false}
      - {label: 正文, name: body, widget: markdown}
      - {label: 标签, name: tags, widget: list, required: false}
      - {label: 发布状态, name: status, widget: boolean, default: true}
